// The umbrella net. Bitwarden's API is 100+ routes; a route that silently stops
// being registered is the failure that leaves every test green. This reads the
// surface off the constructed app -- not off the source -- and CI fails when the
// committed table and the real app disagree.
//
//   node scripts/route-surface.mjs           rewrite the table
//   node scripts/route-surface.mjs --check   fail if it is out of date
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createApp } from '../src/app.ts'

const OUT = fileURLToPath(new URL('../docs/generated/routes.md', import.meta.url))

const routes = [...new Set(createApp().routes.map((r) => `${r.method} ${r.path}`))]
  .filter((r) => !r.startsWith('ALL '))
  .sort()

const table = [
  '---',
  'type: Reference',
  'title: Route surface',
  'description: Every route the app actually registers. Generated, diffed in CI.',
  'status: active',
  '---',
  '',
  '<!-- Generated by scripts/route-surface.mjs. Do not edit. -->',
  '',
  '# Route surface',
  '',
  `${routes.length} routes.`,
  '',
  '| Method | Path |',
  '|---|---|',
  ...routes.map((r) => `| ${r.slice(0, r.indexOf(' '))} | \`${r.slice(r.indexOf(' ') + 1)}\` |`),
  '',
].join('\n')

if (process.argv.includes('--check')) {
  const committed = readFileSync(OUT, 'utf8')
  if (committed !== table) {
    console.error('Route surface changed. Run `npm run routes` and commit the result.\n')
    const a = committed.split('\n')
    const b = table.split('\n')
    for (const line of a.filter((l) => !b.includes(l))) console.error(`- ${line}`)
    for (const line of b.filter((l) => !a.includes(l))) console.error(`+ ${line}`)
    process.exit(1)
  }
  console.log(`Route surface unchanged (${routes.length} routes).`)
} else {
  writeFileSync(OUT, table)
  console.log(`Wrote ${routes.length} routes to docs/generated/routes.md`)
}
